#!/usr/bin/env bash
if [ "$(readlink "$0")" == "" ]; then
    pushd `dirname $0` > /dev/null
    export GD_DIR=`pwd -P`
    popd > /dev/null
else
    export GD_DIR=$(readlink "$0" | xargs dirname)
fi
export ENTRY_DIR=$(pwd)

echo "GD_DIR: ${GD_DIR}"
echo "ENTRY_DIR: ${ENTRY_DIR}"

source "$GD_DIR/lib/version-check"
source "$GD_DIR/lib/reset"
source "$GD_DIR/lib/env"

set-env

[ -n "${ARGS[*]}" ] && ${ARGS[@]}
PID=$!

trap+() {
    func="$1" ; shift
    for sig ; do
        trap "$func $sig" "$sig"
    done
}

proxy() {
    kill -s $1 $PID > /dev/null 2>&1
}

trap+ proxy INT TERM EXIT
