#!/usr/bin/env bash

if [ -n "$CI" ] || [ -n "$NO_COLOR" ]; then
    export COLOR_RESET=""
    export COLOR_BLACK=""
    export COLOR_RED=""
    export COLOR_GREEN=""
    export COLOR_YELLOW=""
    export COLOR_BLUE=""
    export COLOR_MAGENTA=""
    export COLOR_CYAN=""
    export COLOR_WHITE=""
    export COLOR_FADED=""
else
    export COLOR_RESET=$(tput sgr0)
    export COLOR_BLACK=$(tput setaf 0)
    export COLOR_RED=$(tput setaf 1)
    export COLOR_GREEN=$(tput setaf 2)
    export COLOR_YELLOW=$(tput setaf 3)
    export COLOR_BLUE=$(tput setaf 4)
    export COLOR_MAGENTA=$(tput setaf 5)
    export COLOR_CYAN=$(tput setaf 6)
    export COLOR_WHITE=$(tput setaf 7)
    export COLOR_FADED=$(tput setaf 246)
fi

export SYMBOL_CHECKMARK="\xe2\x9c\x93"
export SYMBOL_XMARK="\xe2\x9c\x95"
export SYMBOL_STAR="\xe2\x98\x85"
export SYMBOL_SKULL="\xe2\x98\xa0"
export SYMBOL_RIGHTARROW="\xe2\x9e\x9c"
export SYMBOL_DOTS="\xe2\x81\x98"
export SYMBOL_FROWN="\xe2\x98\xb9"
export SYMBOL_START="\xe2\x9c\xaa"
export SYMBOL_QUESTION="\xe2\x9d\x94"

