#!/usr/bin/env bash
if [ "$(readlink "$0")" == "" ]; then
    pushd `dirname $0` > /dev/null
    export GD_DIR=`pwd -P`
    popd > /dev/null
else
    export GD_DIR=$(readlink "$0" | xargs dirname)
fi
export ENTRY_DIR=$(pwd)
make -C "$GD_DIR" $@
