kind: composition
config:
  git:
    depth: 1
    single-branch: true
spec:
  - deploy.prompts
  - '@bind/deploy.prompts.refspec::git.branch'
  - '@bind/deploy.prompts.directory::git.directory'
  - '@bind/deploy.prompts.directory::docker.context'
  - '@rebind/name::docker.name'
  - git.clone
  - docker.build
