kind: composition
config: # this config is bound to this specific composition and will override all other config
  git:
    depth: 1
    single-branch: true
spec:
  - deploy.prompts
  - '@bind/deploy.prompts.refspec::git.branch'
  - '@bind/deploy.prompts.directory::git.directory'
  - '@rebind/name::docker.name'
  - git.clone
  - docker.build
